-- Depends on 20260801143000_business_admin_access.sql.
-- Razorpay credentials and live transactions are never stored in Postgres.

alter table public.business_organizations add column if not exists billing_country text;
alter table public.business_organizations drop constraint if exists business_organizations_payment_status_check;
alter table public.business_organizations add constraint business_organizations_payment_status_check
  check (payment_status in ('unpaid','manual_confirmed','gateway_confirmed','waived','refunded'));

create table if not exists public.business_payment_proposals (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.business_organizations(id) on delete cascade,
  price_book_id text not null check (price_book_id ~ '^[a-z0-9_]{3,40}$'), billing_country text not null check (billing_country ~ '^[A-Z]{2}$'),
  customer_email text, status text not null default 'draft' check (status in ('draft','approved','paid','expired','cancelled')),
  expires_at timestamptz not null, created_by uuid references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.business_payment_orders (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.business_organizations(id) on delete cascade,
  proposal_id uuid not null references public.business_payment_proposals(id), created_by uuid not null references auth.users(id),
  provider_order_id text not null unique, provider_payment_id text unique, receipt text not null unique check (char_length(receipt) <= 40),
  amount bigint not null check (amount >= 100), currency text not null check (currency ~ '^[A-Z]{3}$'),
  idempotency_key text not null, status text not null check (char_length(status) between 3 and 80),
  verified_at timestamptz, created_at timestamptz not null default now(), unique(created_by,idempotency_key)
);
create table if not exists public.business_payment_webhook_events (
  id bigint generated by default as identity primary key, provider_event_id text not null unique,
  event_type text not null, provider_payment_id text, payload_hash text not null check (payload_hash ~ '^[a-f0-9]{64}$'),
  received_at timestamptz not null default now(), processed_at timestamptz
);
create index if not exists business_payment_orders_org_created_idx on public.business_payment_orders(organization_id,created_at desc);
create index if not exists business_payment_proposals_org_status_idx on public.business_payment_proposals(organization_id,status,expires_at);

alter table public.business_payment_proposals enable row level security;
alter table public.business_payment_orders enable row level security;
alter table public.business_payment_webhook_events enable row level security;
revoke all on public.business_payment_proposals,public.business_payment_orders,public.business_payment_webhook_events from public,anon,authenticated;
revoke all on sequence public.business_payment_webhook_events_id_seq from public,anon,authenticated;
grant all on public.business_payment_proposals,public.business_payment_orders,public.business_payment_webhook_events to service_role;
grant usage,select on sequence public.business_payment_webhook_events_id_seq to service_role;

create or replace function public.business_finalize_razorpay_event(
  p_event_id text,p_event_type text,p_payment_id text,p_order_id text,p_payload_hash text,p_action text
) returns boolean language plpgsql security definer set search_path=''
as $$
declare v_order public.business_payment_orders%rowtype;
begin
  if p_action not in ('activate','fail','refund','dispute','ignore') then raise exception 'Invalid payment action'; end if;
  insert into public.business_payment_webhook_events(provider_event_id,event_type,provider_payment_id,payload_hash)
  values(p_event_id,p_event_type,p_payment_id,p_payload_hash) on conflict(provider_event_id) do nothing;
  if not found then return false; end if;
  select * into v_order from public.business_payment_orders where provider_order_id=p_order_id for update;
  if v_order.id is null then
    update public.business_payment_webhook_events set processed_at=now() where provider_event_id=p_event_id;
    return true;
  end if;
  if p_action='activate' then
    update public.business_payment_orders set provider_payment_id=p_payment_id,status='captured',verified_at=now() where id=v_order.id;
    update public.business_payment_proposals set status='paid',updated_at=now() where id=v_order.proposal_id and organization_id=v_order.organization_id;
    update public.business_organizations set payment_status='gateway_confirmed',pilot_access_status='active',access_updated_at=now() where id=v_order.organization_id;
  elsif p_action in ('fail','refund','dispute') then
    update public.business_payment_orders set provider_payment_id=coalesce(provider_payment_id,p_payment_id),status=p_event_type where id=v_order.id;
    update public.business_organizations set payment_status=case when p_action='refund' then 'refunded' else 'unpaid' end,pilot_access_status='revoked',access_updated_at=now() where id=v_order.organization_id;
  end if;
  update public.business_payment_webhook_events set processed_at=now() where provider_event_id=p_event_id;
  return true;
end $$;
revoke all on function public.business_finalize_razorpay_event(text,text,text,text,text,text) from public,anon,authenticated;
grant execute on function public.business_finalize_razorpay_event(text,text,text,text,text,text) to service_role;

create or replace function public.business_has_effective_access(p_organization_id uuid,p_user_id uuid default auth.uid(),p_require_membership boolean default true)
returns boolean language sql stable security definer set search_path=''
as $$ select exists(select 1 from public.business_organizations o where o.id=p_organization_id and o.status in ('pilot','active')
 and o.pilot_access_status='active' and o.payment_status in ('manual_confirmed','gateway_confirmed','waived')
 and (o.access_expires_at is null or o.access_expires_at>now() or (o.access_grace_until is not null and o.access_grace_until>now()))
 and (not p_require_membership or (p_user_id is not null and exists(select 1 from public.business_organization_members m where m.organization_id=o.id and m.user_id=p_user_id)))) $$;
revoke all on function public.business_has_effective_access(uuid,uuid,boolean) from public,anon;
grant execute on function public.business_has_effective_access(uuid,uuid,boolean) to authenticated,service_role;
