-- Manual business access administration for controlled pilots.
-- No payment gateway, credentials, or seeded users.

alter table public.business_organizations
  add column if not exists employee_type text not null default 'aarya_admissions',
  add column if not exists pilot_access_status text not null default 'pending',
  add column if not exists access_expires_at timestamptz,
  add column if not exists plan_code text not null default 'pilot',
  add column if not exists payment_status text not null default 'unpaid',
  add column if not exists payment_notes text,
  add column if not exists access_updated_at timestamptz not null default now();

do $$
begin
  if not exists (select 1 from pg_constraint where conname='business_organizations_employee_type_check') then
    alter table public.business_organizations add constraint business_organizations_employee_type_check
      check (employee_type in ('aarya_admissions','kabir_lead_followup'));
  end if;
  if not exists (select 1 from pg_constraint where conname='business_organizations_access_status_check') then
    alter table public.business_organizations add constraint business_organizations_access_status_check
      check (pilot_access_status in ('pending','active','revoked','expired'));
  end if;
  if not exists (select 1 from pg_constraint where conname='business_organizations_plan_check') then
    alter table public.business_organizations add constraint business_organizations_plan_check
      check (plan_code in ('pilot','starter','growth','custom'));
  end if;
  if not exists (select 1 from pg_constraint where conname='business_organizations_payment_status_check') then
    alter table public.business_organizations add constraint business_organizations_payment_status_check
      check (payment_status in ('unpaid','manual_confirmed','waived','refunded'));
  end if;
end $$;

create index if not exists business_organizations_access_idx
  on public.business_organizations(pilot_access_status,access_expires_at);

create table if not exists public.business_admin_audit_events (
  id bigint generated by default as identity primary key,
  admin_user_id uuid not null references auth.users(id),
  organization_id uuid references public.business_organizations(id) on delete set null,
  action text not null check (char_length(action) between 3 and 80),
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists business_admin_audit_org_idx
  on public.business_admin_audit_events(organization_id,created_at desc);
create index if not exists business_admin_audit_admin_idx
  on public.business_admin_audit_events(admin_user_id,created_at desc);

alter table public.business_admin_audit_events enable row level security;
revoke all on public.business_admin_audit_events from public,anon,authenticated;
revoke all on sequence public.business_admin_audit_events_id_seq from public,anon,authenticated;
grant all on public.business_admin_audit_events to service_role;
grant usage,select on sequence public.business_admin_audit_events_id_seq to service_role;
