-- Aarya controlled-pilot runtime.
-- Schema-only and safe to re-run: no secrets, credentials, or environment-specific seed data.

create extension if not exists pgcrypto with schema extensions;

create table if not exists public.business_organizations (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 2 and 160),
  root_url text not null check (root_url ~ '^https?://'),
  widget_key uuid not null unique default gen_random_uuid(),
  status text not null default 'pilot' check (status in ('pilot','active','paused','archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.business_organization_members (
  organization_id uuid not null references public.business_organizations(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  role text not null default 'owner' check (role in ('owner','admin','reviewer')),
  created_at timestamptz not null default now(),
  primary key (organization_id,user_id)
);

create table if not exists public.business_approved_knowledge (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.business_organizations(id) on delete cascade,
  source_url text not null check (source_url ~ '^https?://'),
  title text not null default '',
  content text not null check (char_length(content) between 1 and 50000),
  approved boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id,source_url)
);

create table if not exists public.business_conversations (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.business_organizations(id) on delete cascade,
  channel text not null default 'website' check (channel in ('website','email','voice')),
  visitor_name text,
  visitor_email text,
  visitor_phone text,
  status text not null default 'open' check (status in ('open','needs_attention','closed')),
  started_at timestamptz not null default now(),
  last_message_at timestamptz not null default now()
);

create table if not exists public.business_messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null references public.business_conversations(id) on delete cascade,
  sender text not null check (sender in ('visitor','aarya','human')),
  content text not null check (char_length(content) between 1 and 5000),
  source_urls text[] not null default '{}',
  needs_human boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.business_leads (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.business_organizations(id) on delete cascade,
  conversation_id uuid references public.business_conversations(id) on delete set null,
  name text,
  email text,
  phone text,
  course_interest text,
  status text not null default 'new' check (status in ('new','qualified','contacted','closed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (email is not null or phone is not null or name is not null)
);

create table if not exists public.business_attention_items (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.business_organizations(id) on delete cascade,
  conversation_id uuid not null references public.business_conversations(id) on delete cascade,
  reason text not null check (char_length(reason) between 1 and 500),
  status text not null default 'open' check (status in ('open','resolved')),
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

create index if not exists business_org_members_user_idx on public.business_organization_members(user_id,organization_id);
create index if not exists business_knowledge_org_approved_idx on public.business_approved_knowledge(organization_id) where approved;
create index if not exists business_conversations_org_recent_idx on public.business_conversations(organization_id,last_message_at desc);
create index if not exists business_messages_conversation_recent_idx on public.business_messages(conversation_id,created_at);
create index if not exists business_leads_conversation_idx on public.business_leads(conversation_id);
create index if not exists business_leads_org_recent_idx on public.business_leads(organization_id,created_at desc);
create index if not exists business_attention_conversation_idx on public.business_attention_items(conversation_id);
create index if not exists business_attention_org_status_idx on public.business_attention_items(organization_id,status,created_at desc);

alter table public.business_organizations enable row level security;
alter table public.business_organization_members enable row level security;
alter table public.business_approved_knowledge enable row level security;
alter table public.business_conversations enable row level security;
alter table public.business_messages enable row level security;
alter table public.business_leads enable row level security;
alter table public.business_attention_items enable row level security;

drop policy if exists "members read own memberships" on public.business_organization_members;
create policy "members read own memberships" on public.business_organization_members for select to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "members read organizations" on public.business_organizations;
create policy "members read organizations" on public.business_organizations for select to authenticated
using (exists (select 1 from public.business_organization_members m where m.organization_id = business_organizations.id and m.user_id = (select auth.uid())));

drop policy if exists "members read approved knowledge" on public.business_approved_knowledge;
create policy "members read approved knowledge" on public.business_approved_knowledge for select to authenticated
using (exists (select 1 from public.business_organization_members m where m.organization_id = business_approved_knowledge.organization_id and m.user_id = (select auth.uid())));
drop policy if exists "members insert approved knowledge" on public.business_approved_knowledge;
create policy "members insert approved knowledge" on public.business_approved_knowledge for insert to authenticated
with check (exists (select 1 from public.business_organization_members m where m.organization_id = business_approved_knowledge.organization_id and m.user_id = (select auth.uid())));
drop policy if exists "members update approved knowledge" on public.business_approved_knowledge;
create policy "members update approved knowledge" on public.business_approved_knowledge for update to authenticated
using (exists (select 1 from public.business_organization_members m where m.organization_id = business_approved_knowledge.organization_id and m.user_id = (select auth.uid())))
with check (exists (select 1 from public.business_organization_members m where m.organization_id = business_approved_knowledge.organization_id and m.user_id = (select auth.uid())));

drop policy if exists "members read conversations" on public.business_conversations;
create policy "members read conversations" on public.business_conversations for select to authenticated
using (exists (select 1 from public.business_organization_members m where m.organization_id = business_conversations.organization_id and m.user_id = (select auth.uid())));
drop policy if exists "members update conversations" on public.business_conversations;
create policy "members update conversations" on public.business_conversations for update to authenticated
using (exists (select 1 from public.business_organization_members m where m.organization_id = business_conversations.organization_id and m.user_id = (select auth.uid())))
with check (exists (select 1 from public.business_organization_members m where m.organization_id = business_conversations.organization_id and m.user_id = (select auth.uid())));

drop policy if exists "members read messages" on public.business_messages;
create policy "members read messages" on public.business_messages for select to authenticated
using (exists (select 1 from public.business_conversations c join public.business_organization_members m on m.organization_id=c.organization_id where c.id=business_messages.conversation_id and m.user_id=(select auth.uid())));

drop policy if exists "members read leads" on public.business_leads;
create policy "members read leads" on public.business_leads for select to authenticated
using (exists (select 1 from public.business_organization_members m where m.organization_id = business_leads.organization_id and m.user_id = (select auth.uid())));
drop policy if exists "members update leads" on public.business_leads;
create policy "members update leads" on public.business_leads for update to authenticated
using (exists (select 1 from public.business_organization_members m where m.organization_id = business_leads.organization_id and m.user_id = (select auth.uid())))
with check (exists (select 1 from public.business_organization_members m where m.organization_id = business_leads.organization_id and m.user_id = (select auth.uid())));

drop policy if exists "members read attention" on public.business_attention_items;
create policy "members read attention" on public.business_attention_items for select to authenticated
using (exists (select 1 from public.business_organization_members m where m.organization_id = business_attention_items.organization_id and m.user_id = (select auth.uid())));
drop policy if exists "members update attention" on public.business_attention_items;
create policy "members update attention" on public.business_attention_items for update to authenticated
using (exists (select 1 from public.business_organization_members m where m.organization_id = business_attention_items.organization_id and m.user_id = (select auth.uid())))
with check (exists (select 1 from public.business_organization_members m where m.organization_id = business_attention_items.organization_id and m.user_id = (select auth.uid())));

create or replace function public.business_ensure_organization(p_name text,p_root_url text) returns uuid
language plpgsql security definer set search_path=''
as $$
declare v_user uuid := auth.uid(); v_org uuid;
begin
 if v_user is null then raise exception 'Authentication required'; end if;
 if char_length(trim(p_name)) < 2 or char_length(trim(p_name)) > 160 then raise exception 'Invalid organization name'; end if;
 if p_root_url !~ '^https?://' then raise exception 'Invalid organization URL'; end if;
 select organization_id into v_org from public.business_organization_members where user_id=v_user order by created_at limit 1;
 if v_org is null then
   insert into public.business_organizations(name,root_url) values(trim(p_name),trim(p_root_url)) returning id into v_org;
   insert into public.business_organization_members(organization_id,user_id,role) values(v_org,v_user,'owner');
 else
   update public.business_organizations set name=trim(p_name),root_url=trim(p_root_url),updated_at=now() where id=v_org;
 end if;
 return v_org;
end $$;

create or replace function public.aarya_get_approved_knowledge(p_widget_key uuid)
returns table(organization_id uuid,organization_name text,source_url text,title text,content text)
language sql stable security definer set search_path=''
as $$ select o.id,o.name,k.source_url,k.title,k.content from public.business_organizations o join public.business_approved_knowledge k on k.organization_id=o.id where o.widget_key=p_widget_key and o.status in ('pilot','active') and k.approved order by k.updated_at desc limit 10 $$;

create or replace function public.aarya_record_exchange(
 p_widget_key uuid,p_conversation_id uuid,p_question text,p_answer text,p_needs_human boolean,
 p_source_urls text[] default '{}',p_visitor_name text default null,p_visitor_email text default null,
 p_visitor_phone text default null,p_course_interest text default null) returns uuid
language plpgsql security definer set search_path=''
as $$
declare v_org uuid; v_conversation uuid;
begin
 if char_length(trim(p_question)) not between 1 and 2000 then raise exception 'Invalid question'; end if;
 if char_length(trim(p_answer)) not between 1 and 5000 then raise exception 'Invalid answer'; end if;
 select id into v_org from public.business_organizations where widget_key=p_widget_key and status in ('pilot','active');
 if v_org is null then raise exception 'Unknown widget'; end if;
 if p_conversation_id is not null then select id into v_conversation from public.business_conversations where id=p_conversation_id and organization_id=v_org; end if;
 if v_conversation is null then
   insert into public.business_conversations(organization_id,visitor_name,visitor_email,visitor_phone,status)
   values(v_org,nullif(trim(p_visitor_name),''),nullif(lower(trim(p_visitor_email)),''),nullif(trim(p_visitor_phone),''),case when p_needs_human then 'needs_attention' else 'open' end) returning id into v_conversation;
 else
   update public.business_conversations set last_message_at=now(),status=case when p_needs_human then 'needs_attention' else status end,
   visitor_name=coalesce(nullif(trim(p_visitor_name),''),visitor_name),visitor_email=coalesce(nullif(lower(trim(p_visitor_email)),''),visitor_email),visitor_phone=coalesce(nullif(trim(p_visitor_phone),''),visitor_phone) where id=v_conversation;
 end if;
 insert into public.business_messages(conversation_id,sender,content) values(v_conversation,'visitor',trim(p_question));
 insert into public.business_messages(conversation_id,sender,content,source_urls,needs_human) values(v_conversation,'aarya',trim(p_answer),coalesce(p_source_urls,'{}'),p_needs_human);
 if p_needs_human then insert into public.business_attention_items(organization_id,conversation_id,reason) values(v_org,v_conversation,'Aarya could not safely answer from approved knowledge or the visitor requested human review.'); end if;
 if nullif(trim(p_visitor_name),'') is not null or nullif(trim(p_visitor_email),'') is not null or nullif(trim(p_visitor_phone),'') is not null then
   insert into public.business_leads(organization_id,conversation_id,name,email,phone,course_interest) values(v_org,v_conversation,nullif(trim(p_visitor_name),''),nullif(lower(trim(p_visitor_email)),''),nullif(trim(p_visitor_phone),''),nullif(trim(p_course_interest),''));
 end if;
 return v_conversation;
end $$;

revoke all on public.business_organizations,public.business_organization_members,public.business_approved_knowledge,
 public.business_conversations,public.business_messages,public.business_leads,public.business_attention_items from anon;
grant select,insert,update,delete on public.business_organizations,public.business_organization_members,public.business_approved_knowledge,
 public.business_conversations,public.business_messages,public.business_leads,public.business_attention_items to authenticated;
grant usage,select on sequence public.business_messages_id_seq to authenticated;

revoke all on function public.business_ensure_organization(text,text) from public,anon;
grant execute on function public.business_ensure_organization(text,text) to authenticated,service_role;
revoke all on function public.aarya_get_approved_knowledge(uuid) from public;
grant execute on function public.aarya_get_approved_knowledge(uuid) to anon,authenticated,service_role;
revoke all on function public.aarya_record_exchange(uuid,uuid,text,text,boolean,text[],text,text,text,text) from public;
grant execute on function public.aarya_record_exchange(uuid,uuid,text,text,boolean,text[],text,text,text,text) to anon,authenticated,service_role;
