-- Private consultation requests for the consultation-led business launch.
-- No payment, external notification provider, or customer access is activated here.

create table if not exists public.business_solution_requests (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid references public.business_organizations(id) on delete set null,
  contact_name text not null check (char_length(contact_name) between 2 and 120),
  company_name text not null check (char_length(company_name) between 2 and 160),
  work_email text not null check (char_length(work_email) between 5 and 254),
  phone text,
  country text not null check (char_length(country) between 2 and 100),
  timezone text not null check (char_length(timezone) between 1 and 100),
  preferred_contact_channel text not null check (preferred_contact_channel in ('email','phone','whatsapp','video_call')),
  best_contact_time text not null check (char_length(best_contact_time) between 1 and 120),
  selected_solution text not null check (char_length(selected_solution) between 2 and 80),
  workflow_problem text not null check (char_length(workflow_problem) between 20 and 3000),
  monthly_volume text not null check (monthly_volume in ('under_100','100_500','501_2000','over_2000','unknown')),
  systems text[] not null default '{}',
  other_systems text,
  languages text not null check (char_length(languages) between 1 and 300),
  target_outcome text not null check (char_length(target_outcome) between 10 and 500),
  timeline text not null check (timeline in ('exploring','within_30_days','one_to_three_months','later')),
  budget_band text not null check (budget_band in ('under_100_usd','100_300_usd','301_750_usd','751_2000_usd','over_2000_usd','custom','unknown')),
  custom_budget text,
  consent_to_contact boolean not null check (consent_to_contact),
  consented_at timestamptz not null,
  source text not null default 'business_consultation_page',
  status text not null default 'new' check (status in ('new','contacted','discovery','proposal','payment_pending','setup','active','paused','closed')),
  owner_notes text,
  notification_status text not null default 'pending' check (notification_status in ('pending','notified','failed')),
  ip_hash text not null check (char_length(ip_hash)=64),
  request_fingerprint text not null unique check (char_length(request_fingerprint)=64),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.business_solution_request_events (
  id bigint generated by default as identity primary key,
  request_id uuid not null references public.business_solution_requests(id) on delete cascade,
  from_status text,
  to_status text not null,
  actor_user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists business_solution_requests_status_recent_idx on public.business_solution_requests(status,created_at desc);
create index if not exists business_solution_requests_ip_recent_idx on public.business_solution_requests(ip_hash,created_at desc);
create index if not exists business_solution_requests_email_idx on public.business_solution_requests(lower(work_email));
create index if not exists business_solution_request_events_request_idx on public.business_solution_request_events(request_id,created_at);

alter table public.business_solution_requests enable row level security;
alter table public.business_solution_request_events enable row level security;

create or replace function public.record_business_solution_request_status()
returns trigger language plpgsql security definer set search_path=''
as $$
begin
  if tg_op='INSERT' then
    insert into public.business_solution_request_events(request_id,from_status,to_status)
    values(new.id,null,new.status);
  elsif new.status is distinct from old.status then
    insert into public.business_solution_request_events(request_id,from_status,to_status)
    values(new.id,old.status,new.status);
  end if;
  new.updated_at=now();
  return new;
end $$;

drop trigger if exists business_solution_request_status_audit on public.business_solution_requests;
create trigger business_solution_request_status_audit
before insert or update on public.business_solution_requests
for each row execute function public.record_business_solution_request_status();

revoke all on public.business_solution_requests,public.business_solution_request_events from public,anon,authenticated;
revoke all on sequence public.business_solution_request_events_id_seq from public,anon,authenticated;
grant all on public.business_solution_requests,public.business_solution_request_events to service_role;
grant usage,select on sequence public.business_solution_request_events_id_seq to service_role;
revoke all on function public.record_business_solution_request_status() from public,anon,authenticated;
